[package]
name = "mitos-gui"
version = "0.1.0"
edition = "2021"
authors = ["Shark <banor3331@gmail.com>"]
description = "Lightweight, modern Wayland compositor and desktop shell for MITOS"

[dependencies]
smithay = { version = "0.7", features = [
    "wayland_frontend",
    "desktop",
    "backend_winit",
    "backend_drm",
    "backend_gbm",
    "backend_egl",
    "backend_session_libseat",
    "backend_libinput",
    "renderer_gl",
] }


wayland-protocols = { version = "0.32", features = ["server"] }

calloop = "0.14"
tracing = "0.1"
tracing-subscriber = "0.3"
ab_glyph = "0.2"

image = { version = "0.25", default-features = false, features = ["png"] }
notify = "6"
