name: Build mitos-gui

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GUI dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libudev-dev \
            libseat-dev \
            libinput-dev \
            libpixman-1-dev \
            libgbm-dev \
            libdrm-dev\
            libwayland-dev \
            libxkbcommon-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libxcursor-dev \
            libxinerama-dev \
            libegl1-mesa-dev \
            libgl1-mesa-dev

      - name: Build
        run: cargo build --release
